*: add TTL support
vimeo/galaxycache pull request #25
Opened 2021-12-15 09:08 UTC by GiedriusS

Add TTL support for keys. Implemented for our use case in https://github.com/thanos-io/thanos/ where cached data can potentially change over time. Thus, some kind of TTL mechanism is needed. Implemented it in the same fashion as https://github.com/mailgun/groupcache - deadline for keys is embedded in the value in the LRU cache. On retrieval, the deadline is checked and we are past it then we remove that key.

In HTTP the expiry date is exposed via an extra header. With gRPC, a new field has been added.

Note: this implies that users will have a somewhat synchronized time across nodes in the group. Otherwise, extra fetches might happen or the keys might not ever expire.

2021-12-16 20:23 UTC, dfinkel requested changes
First of all, Thanks for sending this PR!

With that said, I have some mixed feelings about supporting TTLs in Galaxycache in general, and the approach in this PR specifically.

First, my general opinion: Galaxycache works really well because it can treat everything as opaque and immutable. At times, expiration is better handled by changing the cache-key. (e.g. we (Vimeo's Core Services team) wrote [this blog post](https://medium.com/vimeo-engineering-blog/video-metadata-caching-at-vimeo-a54b25f0b304) about a scheme we've used for breaking time into epochs (per-key) instead of introducing TTLs to galaxycache.

However, there are still some places where TTLs would be useful, so I think it would be useful to have optional TTL support on some galaxies. (and we can come up with some advice on when to choose a TTL vs cleverly chosen keys)

With respect to this PR, unfortunately, I feel that there are too many breaking changes as-is. (I've noted a few in my comments)

In particular, I think that the `Codec` interface is a key public interface that would break a lot of client code if it changed much. However, I do like the change to `RemoteGetter`, I don't expect there to be many implementations of that outside this repository, so returning a new value is reasonable. (although we might want to make that new return-value a struct so we don't have to break the interface every time we add a new field)

I think an improvement would be to instead add a `GetWithExpiry` method to `Galaxy` and create an `ExpiringBackendGetter` interface for users to implement. (that has a `GetWithExpiry` method instead of a `Get` method). We'd have galaxycache type-switch so it prefers `GetWithExpiry` implementations.

With respect to `lru.Cache`, I think we should copy the existing implementation and add an `lru.CacheWithExpiry`, so galaxies that have `BackendGetter` implementations rather than `ExpiringBackendGetter` implementations wouldn't need to track the additional timestamps.

One thing that one of my teammates pointed out (@arodland ) is that the LRU supporting expiration should track expiring entries so upon eviction we don't evict an unexpired entry if there are any expired entries. (we might need a tree-map or skip-list of some sort to make that efficient for both insertion of arbitrary TTLs and eviction of the oldest one)

2021-12-17 08:11 UTC, GiedriusS commented
cc @akanshat

2022-01-18 10:48 UTC, GiedriusS commented
Thank you for your thorough review, we will try the epochs approach and come back to you.

2025-04-09 17:34 UTC, sergiosalvatore commented
Given the inactivity here, I'm going to close the PR -- feel free to continue the discussion and re-open if you need.

2025-04-09 17:34 UTC, closed without merging

2025-12-17 23:01 UTC, dfinkel commented
Wow, somehow this PR just turned 4 years old.

... and we've just tagged a stable `v1.4.0` release with TTL support (and the ability to set explicit expirations) 
https://github.com/vimeo/galaxycache/releases/tag/v1.4.0